### ISSUE TITLE
Import questions dialog has a second unstyled close button

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/enigma-materia-widget#6]
![screen shot 2019-02-14 at 11 49 37 am](https://user-images.githubusercontent.com/73480/52802920-e3445780-304e-11e9-8bc6-07e3910ef4bf.png)

**Comment by FrenjaminBanklin** [comment]
@iturgeon - I'm not able to reproduce this using the current release for Enigma. What commit are you running?

**Comment by FrenjaminBanklin** [comment]
Looks like this was resolved at some point and doesn't happen in the current release. Closing.
