### ISSUE TITLE
Editing the title in the creator starts the tutorial

### ISSUE THREAD

**Issue by iturgeon** [ucfopen/enigma-materia-widget#7]
![2019-02-14 11 51 06](https://user-images.githubusercontent.com/73480/52802979-04a54380-304f-11e9-8297-2f3c44ee2989.gif)

**Comment by iturgeon** [comment]
This is a problem in a old version, IGNORE ME.

**Comment by FrenjaminBanklin** [comment]
Looks like this was resolved at some point and doesn't happen in the current release. Closing.
